### ISSUE TITLE
DESCRIPTION update

### ISSUE THREAD

**Issue by josherrickson** [atewari7/rlemon#23]
I've updated the DESCRIPTION file both for license, and to update to the `authors@R` notation. Please double check your names/roles, and update email if desired.

- [x] Aditya
- [x] Arav

(PS: `ctr`, or creator, is the flag used for current maintainer, even if that person isn't the original creator.)

**Comment by arav-agarwal2** [comment]
I'm all set on my end; Just added my email in case anyone wants to contact me as well.
