### ISSUE TITLE
runner functions

### ISSUE THREAD

**Issue by josherrickson** [atewari7/rlemon#30]
My understanding of the runner functions was that the call stack was, e.g.

`MaxFlow(..., algorithm = "PreFlow")` -> 
`PreFlowRunner(...)` ->
`.Call(_rlemon_PreFlowRunner, ...)`

However, looking at the code, it looks like we mostly bypass the R Runner:

https://github.com/josherrickson/rlemon/blob/dfaf03c8a9fae99d4041ef58a6037d7dc318bca3/R/maxflow.R#L33-L37

I'd like to keep using the R runners as a way for users to directly access the LEMON if desired, without any input checks and any other potential cleanups that we do.

**Comment by josherrickson** [comment]
Assigning to @arav-agarwal2 for comment in case I'm missing something.

**Comment by arav-agarwal2** [comment]
When we stopped exporting the C++ functions, I was under the impression that those R functions are missing from being accessed directly. 

Is this not the case?

**Comment by josherrickson** [comment]
R's got a variation of public/private objects in packages. A function that is explicitly exported is able to be called directly (`MaxFlow()`) after loading the package (with `library()` or `require()`) or may at any time (even if the package isn't loaded) be called with the double colon notation, e.g. `rlemon::MaxFlow()`.

Alternatively, any object or function that isn't explicitly exported can be called at anytime using the triple colon notation, e.g. `rlemon:::PreFlowRunner`. It can never be called alone, e.g. `PreFlowRunner` will always* fail.

I like the idea of the package supporting two differences interfaces:

1. A direct circuit to LEMON in which we guarantee zero pre- and zero post-processing.
2. A slightly more user-friendly/R-style interface in which we do input checks. (and in the future, may do other pre/post processing).

Typically the way this is done in R is for an exported function `foo()`, there is a not exported function `.foo()` which does most of the work. We could use this exact mannerism in this case, or we could stick with the runners being algorithm specific.

Let me think on this.
